services:
  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-container
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
    depends_on:
      - backend

volumes:
  mongodata: